cloud:
  name: "local"
enabled: true
appsFolder: k8s
services:
  mongodb-operator-app:
    fullName: mongodb-operator-app
    argocdProject: mcas
    repoBranch: main
    repoUrl: https://github.com/tuthan/argocd-app-templates.git
    svcNamespace: mongodb
    valueRepoUrl: https://github.com/tuthan/multi-cloud-agnostic-sample.git
    valueBranch: main
    yamlPath: mongodb-operator/
    syncWave: "-5"
  mongodb-app:
    fullName: mongodb-app
    argocdProject: mcas
    repoBranch: main
    repoUrl: https://github.com/tuthan/argocd-app-templates.git
    svcNamespace: mongodb
    valueRepoUrl: https://github.com/tuthan/multi-cloud-agnostic-sample.git
    valueBranch: main
    yamlPath: mongodb/
    syncWave: "-1"
  mongodb-sample-app:
    fullName: mdb-sample-app
    argocdProject: mcas
    repoBranch: main
    repoUrl: https://github.com/tuthan/argocd-app-templates.git
    svcNamespace: mongodb
    valueRepoUrl: https://github.com/tuthan/multi-cloud-agnostic-sample.git
    valueBranch: main
    yamlPath: mdb-sample-app/
    syncWave: "1"
